# Site settings
baseURL = "https://sieker-portfolio.netlify.app/"
languageCode = "en-us"
title = "Christoph"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-180686344-1"

# Enter your disqus shortname to enable comments
disqusShortname = "Siekerportfolio"

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Christoph Sieker"
  description = "MFA student at LBS"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "/img/favicon_LBS.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "Christoph Sieker"
    subtitle = "Portfolio Website"
    menu = "Menu"
    # Optional logo as brand stored in img/
    #logo = "London_Business_School_Logo.png"

    [[params.navigation.links]]
      #name = "Home"
      #url = "#"

    [[params.navigation.links]]
      name = "Covid data"
      url = "blogs/blog5"

    [[params.navigation.links]]
      name = "US Presidential Approval Rates"
      url = "blogs/blog6"

    [[params.navigation.links]]
      name = "California Contributors"
      url = "blogs/blog7"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
     [[params.navigation.links]]
        name = "Wisdom of alcohol spreads across the globe"
        url = "blogs/blog9"

      [[params.navigation.links]]
        name = "Airbnb Map Singapore"
        url = "blogs/blog8"
        
        [[params.navigation.links]]
        name = "Boris goes Bicycle"
        url = "blogs/blog11"
        
    # Button Style 1
    [[params.navigation.button1]]
      name = "Home"
      url = "#"

    # Button Style 2
    [[params.navigation.button2]]
      name = "CV"
      url = "blogs/CV Christoph Sieker.pdf"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Hi, my name is Christoph"
    subtitle = "This is my portfolio website"
    buttonText = "Get Started"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
    
    [[params.tiles.showcase]]
      title = "Covid data"
      subtitle = "What influences the impact of covid on health?"
      image = "Mask_v1.jpg"
      url = "blogs/blog5"

    [[params.tiles.showcase]]
      title = "US Presidential Approval Rates"
      subtitle = "Obama vs. Trump"
      image = "TrumpObama_v1.jpg"
      url = "blogs/blog6"

    [[params.tiles.showcase]]
      title = "California Contributors - US Election 2016"
      subtitle = "Trump vs. Clinton"
      image = "TrumpClinton_v1.jpg"
      url = "blogs/blog7"

    [[params.tiles.showcase]]
      title = "Wisdom of alcohol spreads across the globe"
      subtitle = "Different countries, different cultures, different drinking habits"
      image = "Drinks_v1.jpg"
      url = "blogs/blog9"

    [[params.tiles.showcase]]
      title = "Airbnb Map Singapore"
      subtitle = "Prices of Airbnb listings"
      image = "SGP_v1.jpg"
      url = "blogs/blog8"

    [[params.tiles.showcase]]
      title = "Boris goes Bicycle"
      subtitle = "TfL bike sharing"
      image = "Boris_v1.jpg"
      url = "blogs/blog11"
    # You can make more showcases by copy and pasting the code above

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = true
    title = "My journey to LBS and beyond"
    subtitle = """
    Student. Adventurer. European. Born and raised in the heart of Europe, I'm aming to spread the values
    of the French Revolution across the globe - Liberté, Egalité, Fraternité. In order to collaborate,
    feel free to contact me or have a glance on my CV."""
    
    buttonText = "Download my CV"
    url = "blogs/CV Christoph Sieker.pdf"


  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Send message"
    buttonClear = "Clear"
    formEmail = "csieker.mfa2021@london.edu"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "csieker.mfa2021@london.edu"

    [[params.contact.phone]]
    title = "Phone (London Business School)"
    phone = "020 7000 7000"

    [[params.contact.address]]
    title = "Address"
    street = "Cavendish Buidlings 20, Gilbert Street"
    city = " W1K 5HH London"
    country = "United Kingdom"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Christoph Sieker 2020"

    # Uses font awesome icons
    #[[params.footer.social]]
     # icon = "fa-twitter"
      #url= "https://www.twitter.com"
      #label = "Twitter"

    [[params.footer.social]]
      icon = "fa-facebook"
      url= "https://www.facebook.com/ChristophAlexanderSieker"
      label = "Facebook"

    [[params.footer.social]]
      icon = "fa-instagram"
      url= "https://www.instagram.com/christoph_sieker"
      label = "Instagram"
    
    [[params.footer.social]]
      icon = "fa-github"
      url= "https://www.github.com"
      label = "GitHub"

    [[params.footer.social]]
      icon = "fa-linkedin"
      url= "https://www.linkedin.com/in/christoph-sieker/"
      label = "LinkedIn"

    [[params.footer.quicklinks]]
      text = "Design: "
      url= "https://www.html5up.net"
      alt = "HTML5 UP"
